global using System.Net;
global using System.Text;
global using Microsoft.Extensions.Logging.Abstractions;
global using LiveChartsCore.SkiaSharpView;
global using RunescapeTools.Application.Favourites;
global using RunescapeTools.Application.Market;
global using RunescapeTools.Application.MoneyMaking;
global using RunescapeTools.Application.Profiles;
global using RunescapeTools.Application.Training;
global using RunescapeTools.Core.Favourites;
global using RunescapeTools.Core.Market;
global using RunescapeTools.Core.MoneyMaking;
global using RunescapeTools.Core.MoneyMaking.Methods;
global using RunescapeTools.Core.Profiles;
global using RunescapeTools.Core.Training;
global using RunescapeTools.Infrastructure.Configuration;
global using RunescapeTools.Infrastructure.Market;
global using RunescapeTools.Infrastructure.Persistence;
global using RunescapeTools.Infrastructure.Profiles;
global using RunescapeTools.Infrastructure.Training;
global using RunescapeTools.Wpf.ViewModels;
global using RunescapeTools.Wpf.Views;
global using NUnit.Framework;
global using RunescapeTools.Tests.TestSupport.Fakes;
global using static RunescapeTools.Tests.TestSupport.Builders.MarketTestData;
global using static RunescapeTools.Tests.TestSupport.Builders.TrainingTestData;
global using static RunescapeTools.Tests.TestSupport.Builders.ProfileTestData;
global using RunescapeTools.Tests.TestSupport;
